(define (problem RechargingRobotsProb)
    (:domain RechargingRobotsDom)
    (:objects
        robot1 robot2 robot3 - robot
        room11 room12 room13 room21 room22 room23 room31 room32 room33 - location
        cfg - config)
    ;; 3x3 grid of rooms
    ;; robots in two corners and center
    ;; guard every room
    (:init 
        (= (loc robot1) room11)
        (= (loc robot2) room22)
        (= (loc robot3) room33)
        (not (stopped robot1))
        (not (stopped robot2))
        (not (stopped robot3))
        (= (battery-level robot1) 0)
        (= (battery-level robot2) 10)
        (= (battery-level robot3) 0)
        (CONNECTED room11 room12)
        (CONNECTED room12 room13)
        (CONNECTED room21 room22)
        (CONNECTED room22 room23)
        (CONNECTED room31 room32)
        (CONNECTED room32 room33)
        (CONNECTED room11 room21)
        (CONNECTED room21 room31)
        (CONNECTED room12 room22)
        (CONNECTED room22 room32)
        (CONNECTED room13 room23)
        (CONNECTED room23 room33)
        (not (config-fullfilled cfg))
        (GUARD-CONFIG cfg room11)
        (GUARD-CONFIG cfg room12)
        (GUARD-CONFIG cfg room13)
        (GUARD-CONFIG cfg room21)
        (GUARD-CONFIG cfg room22)
        (GUARD-CONFIG cfg room23)
        (GUARD-CONFIG cfg room31)
        (GUARD-CONFIG cfg room32)
        (GUARD-CONFIG cfg room33)
        (= move-cost 1)
        (= recharge-cost 1)
        (= total-cost 0))

    (:goal (and (config-fullfilled cfg)
        (not (stopped robot1))
        (not (stopped robot2))
        (not (stopped robot3))
        (= (loc robot1) room31))
    )
)